const navStrip1 = [
    { title: "Home", link: "/" },
    { title: "About Us", link: "/about" },
    { title: "Administration", link: "/administration" },
    { title: "Academics", link: "/academics" },
    { title: "IQAC", link: "/iqac" },
    { title: "NIRF", link: "/nirf" },
    { title: "ARIIA", link: "/ariia" },
    { title: "Placements", link: "/placements" },
    { title: "Contact Us", link: "/contact-us" },
    { title: "Kosa", link: "/kosa" },
    { title: "Examination Cell", link: "/examination-cell" },
    { title: "Testimonials", link: "/testimonials" },
    { title: "Student Services", link: "/student-services" },
    { title: "Covid-19 Best Practices", link: "/covid-19-best-practices" },
    { title: "Faq", link: "/faqs" },
    { title: "Search", link: "/search" },
    // new links
    { title: "Online services", link: "/student-services/#online-services" },
    { title: "UNNT BHARAT ABHIYAN 2.0", link: "/student-services/#UNNT-BHARAT-ABHIYAN-2.0" },
    { title: "UGC Women's Studies Center", link: "/student-services/#UGC-Women's-Studies-Center" },
    { title: "Statutroy Cells", link: "/student-services/#Statutroy-Cells" },
    { title: "Red Ribbon Club", link: "/student-services/#Red-Ribbon-Club" },
    { title: "Consumer Club", link: "/student-services/#Consumer-Club" },
    { title: "NCC", link: "/student-services/#NCC" },
    { title: "NSS", link: "/student-services/#NSS" },
    { title: "Dramatic Association", link: "/student-services/#Dramatic-Association" },
    { title: "Eco Club", link: "/student-services/" },
    { title: "", link: "/student-services/#Eco-Club" },
    { title: "", link: "/student-services/" },
    { title: "", link: "/student-services/" },
    { title: "", link: "/student-services/" },
    { title: "", link: "/student-services/" },
    { title: "", link: "/student-services/" },
    { title: "", link: "/student-services/" },
    { title: "", link: "/student-services/" },
    { title: "", link: "" },
  ];